name: Run Unit Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Run tests
      run: |
        pytest tests/test_cadenas.py

    - name: Upload test results
      if: always() # Ensure this step runs even if tests fail
      uses: actions/upload-artifact@v2
      with:
        name: test-results
