name: Run Selenium Test

on:
  workflow_dispatch:
  push:
    branches:
      - main   # o la rama donde trabajes
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"   # o la versión que uses

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Run Selenium test
        run: python test.py
